version: '3.4'

services:
  progress.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 7119:443
      - 7118:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU6-ubuntu-20.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>
    volumes:
      - "E:/progress-api/db/data:/var/opt/mssql/data"
      - "E:/progress-api/db/log:/var/opt/mssql/log"
      - "E:/progress-api/db/secrets:/var/opt/mssql/secrets"