// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progress.Application.Persistence;

#nullable disable

namespace Progress.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230311105711_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("572ba72e-87df-45bf-9496-a2b9d8962c7d"),
                            DisplayColor = "#000000",
                            Name = "Arcane Magic"
                        },
                        new
                        {
                            Id = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            DisplayColor = "#000000",
                            Name = "Body Enhancement"
                        },
                        new
                        {
                            Id = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            DisplayColor = "#000000",
                            Name = "Healing Magic"
                        },
                        new
                        {
                            Id = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            DisplayColor = "#000000",
                            Name = "Cosmic Magic"
                        },
                        new
                        {
                            Id = new Guid("cdb7b315-0277-451c-9ff0-ea5f1fce8c25"),
                            DisplayColor = "#000000",
                            Name = "Aura"
                        },
                        new
                        {
                            Id = new Guid("f8362bfc-6004-43df-827f-17f21203c6f3"),
                            DisplayColor = "#000000",
                            Name = "Teleportation Magic"
                        },
                        new
                        {
                            Id = new Guid("65728378-090f-4c29-9e87-b282f489d028"),
                            DisplayColor = "#000000",
                            Name = "Perception Aura"
                        },
                        new
                        {
                            Id = new Guid("b1cbe616-e004-4b34-97eb-3d11d2f5f059"),
                            DisplayColor = "#000000",
                            Name = "Ashen Magic"
                        },
                        new
                        {
                            Id = new Guid("29543eb0-73d9-4fd5-8abc-1ebd3c92d9e3"),
                            DisplayColor = "#000000",
                            Name = "FireMagic"
                        },
                        new
                        {
                            Id = new Guid("e5451fe8-a092-45bf-9bbd-728fb10ed6ff"),
                            DisplayColor = "#000000",
                            Name = "Space Magic"
                        },
                        new
                        {
                            Id = new Guid("f8f302ab-7ed7-47a9-85c1-2d570478a99a"),
                            DisplayColor = "#000000",
                            Name = "Flesh Magic"
                        },
                        new
                        {
                            Id = new Guid("4538069f-9680-4b26-84a4-e608d1c86606"),
                            DisplayColor = "#000000",
                            Name = "Mind Magic"
                        },
                        new
                        {
                            Id = new Guid("12696ef5-a857-466f-a618-43ee092816ee"),
                            DisplayColor = "#000000",
                            Name = "Ice Magic"
                        },
                        new
                        {
                            Id = new Guid("94cb02e4-43dc-4021-95ac-d9d5bc6512d6"),
                            DisplayColor = "#000000",
                            Name = "Lava Magic"
                        },
                        new
                        {
                            Id = new Guid("11751928-c2d3-4939-9692-05f578af3d00"),
                            DisplayColor = "#000000",
                            Name = "Earth Magic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
