// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progress.Application.Persistence;

#nullable disable

namespace Progress.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230104120519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RewardExp")
                        .HasColumnType("int");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TreeId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("TreeId");

                    b.HasIndex("TreeId1")
                        .IsUnique()
                        .HasFilter("[TreeId1] IS NOT NULL");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Subtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RewardExp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("Subtasks");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Quest", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Quest", null)
                        .WithMany("Children")
                        .HasForeignKey("QuestId");

                    b.HasOne("Progress.Application.Persistence.Entities.Tree", "Tree")
                        .WithMany("Quests")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progress.Application.Persistence.Entities.Tree", null)
                        .WithOne("RootQuest")
                        .HasForeignKey("Progress.Application.Persistence.Entities.Quest", "TreeId1");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Subtask", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Quest", "Quest")
                        .WithMany("Subtasks")
                        .HasForeignKey("QuestId");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Quest", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Tree", b =>
                {
                    b.Navigation("Quests");

                    b.Navigation("RootQuest");
                });
#pragma warning restore 612, 618
        }
    }
}
