// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progress.Application.Persistence;

#nullable disable

namespace Progress.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230327095914_AddStatsAndSkillpointsToCharacterStatus")]
    partial class AddStatsAndSkillpointsToCharacterStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("572ba72e-87df-45bf-9496-a2b9d8962c7d"),
                            DisplayColor = "#000000",
                            Name = "Arcane Magic"
                        },
                        new
                        {
                            Id = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            DisplayColor = "#000000",
                            Name = "Body Enhancement"
                        },
                        new
                        {
                            Id = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            DisplayColor = "#000000",
                            Name = "Healing Magic"
                        },
                        new
                        {
                            Id = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            DisplayColor = "#000000",
                            Name = "Cosmic Magic"
                        },
                        new
                        {
                            Id = new Guid("cdb7b315-0277-451c-9ff0-ea5f1fce8c25"),
                            DisplayColor = "#000000",
                            Name = "Aura"
                        },
                        new
                        {
                            Id = new Guid("f8362bfc-6004-43df-827f-17f21203c6f3"),
                            DisplayColor = "#000000",
                            Name = "Teleportation Magic"
                        },
                        new
                        {
                            Id = new Guid("65728378-090f-4c29-9e87-b282f489d028"),
                            DisplayColor = "#000000",
                            Name = "Perception Aura"
                        },
                        new
                        {
                            Id = new Guid("b1cbe616-e004-4b34-97eb-3d11d2f5f059"),
                            DisplayColor = "#000000",
                            Name = "Ashen Magic"
                        },
                        new
                        {
                            Id = new Guid("29543eb0-73d9-4fd5-8abc-1ebd3c92d9e3"),
                            DisplayColor = "#000000",
                            Name = "Fire Magic"
                        },
                        new
                        {
                            Id = new Guid("e5451fe8-a092-45bf-9bbd-728fb10ed6ff"),
                            DisplayColor = "#000000",
                            Name = "Space Magic"
                        },
                        new
                        {
                            Id = new Guid("f8f302ab-7ed7-47a9-85c1-2d570478a99a"),
                            DisplayColor = "#000000",
                            Name = "Flesh Magic"
                        },
                        new
                        {
                            Id = new Guid("4538069f-9680-4b26-84a4-e608d1c86606"),
                            DisplayColor = "#000000",
                            Name = "Mind Magic"
                        },
                        new
                        {
                            Id = new Guid("12696ef5-a857-466f-a618-43ee092816ee"),
                            DisplayColor = "#000000",
                            Name = "Ice Magic"
                        },
                        new
                        {
                            Id = new Guid("94cb02e4-43dc-4021-95ac-d9d5bc6512d6"),
                            DisplayColor = "#000000",
                            Name = "Lava Magic"
                        },
                        new
                        {
                            Id = new Guid("11751928-c2d3-4939-9692-05f578af3d00"),
                            DisplayColor = "#000000",
                            Name = "Earth Magic"
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnspentStatpoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            UnspentStatpoints = 25
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseStatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalculationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CharacterStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcePointsPerBaseStatPoint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterStatusId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70eaef56-21c1-494d-a0ba-312478c19428"),
                            BaseStatName = "Vitality",
                            CalculationName = "Health",
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Health",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("f8a10c54-df2b-4658-9e37-ff772a55aea3"),
                            BaseStatName = "Endurance",
                            CalculationName = "Stamina",
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Stamina",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("97f54c26-273e-47fc-b00f-7c5ad5b6cfae"),
                            BaseStatName = "Wisdom",
                            CalculationName = "Mana",
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Mana",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("741e7652-0c8e-4cb8-8ac4-b298637ae6c2"),
                            BaseStatName = "Vitality",
                            CalculationName = "Health",
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Mana (Essence)",
                            ResourcePointsPerBaseStatPoint = 10
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterStatusId");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bf1d8dd-7cc3-486d-bb26-0bde4ee439df"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Vitality",
                            Value = 3800
                        },
                        new
                        {
                            Id = new Guid("ab85915d-e66f-4460-96af-e90f171ccab5"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Endurance",
                            Value = 600
                        },
                        new
                        {
                            Id = new Guid("de4b423f-4718-4e26-9d75-14f4a1581b37"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Strength",
                            Value = 860
                        },
                        new
                        {
                            Id = new Guid("20cce93e-f883-4860-be2f-4cdbd0c6e3be"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Dexterity",
                            Value = 610
                        },
                        new
                        {
                            Id = new Guid("047e7614-496d-4519-a784-6dec5e753571"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Intelligence",
                            Value = 3770
                        },
                        new
                        {
                            Id = new Guid("c6474033-2e4c-4805-95f3-4fe22e9de88a"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Wisdom",
                            Value = 4000
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.OwnsOne("Progress.Application.Persistence.Entities.BasicInformation", "BasicInformation", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CharacterStatusId");

                            b1.ToTable("CharacterStatuses");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatusId");

                            b1.HasData(
                                new
                                {
                                    CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                                    Name = "Ilea Spears",
                                    Title = "Dragonslayer"
                                });
                        });

                    b.OwnsOne("Progress.Application.Persistence.Entities.UnspentSkillpoints", "UnspentSkillpoints", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CoreSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("FourthTierGeneralSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("FourthTierSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("ThirdTierGeneralSkillpoints")
                                .HasColumnType("int");

                            b1.HasKey("CharacterStatusId");

                            b1.ToTable("CharacterStatuses");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatusId");

                            b1.HasData(
                                new
                                {
                                    CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                                    CoreSkillpoints = 10,
                                    FourthTierGeneralSkillpoints = 1,
                                    FourthTierSkillpoints = 1,
                                    ThirdTierGeneralSkillpoints = 3
                                });
                        });

                    b.Navigation("BasicInformation");

                    b.Navigation("UnspentSkillpoints");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Resource", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.CharacterStatus", null)
                        .WithMany("Resources")
                        .HasForeignKey("CharacterStatusId");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Stat", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.CharacterStatus", null)
                        .WithMany("Stats")
                        .HasForeignKey("CharacterStatusId");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
