// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progress.Application.Persistence;

#nullable disable

namespace Progress.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230404141316_AddSkillsToSeededClass")]
    partial class AddSkillsToSeededClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorySkill", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CategorySkill", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriesId = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            SkillsId = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3")
                        },
                        new
                        {
                            CategoriesId = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            SkillsId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224")
                        },
                        new
                        {
                            CategoriesId = new Guid("cdb7b315-0277-451c-9ff0-ea5f1fce8c25"),
                            SkillsId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e")
                        },
                        new
                        {
                            CategoriesId = new Guid("f8362bfc-6004-43df-827f-17f21203c6f3"),
                            SkillsId = new Guid("e8b05991-c7f1-faf9-91e1-d525370c912c")
                        },
                        new
                        {
                            CategoriesId = new Guid("cdb7b315-0277-451c-9ff0-ea5f1fce8c25"),
                            SkillsId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee")
                        },
                        new
                        {
                            CategoriesId = new Guid("65728378-090f-4c29-9e87-b282f489d028"),
                            SkillsId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee")
                        },
                        new
                        {
                            CategoriesId = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            SkillsId = new Guid("7c893d4b-246d-c304-9198-49a886554a85")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("7c893d4b-246d-c304-9198-49a886554a85")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("7c893d4b-246d-c304-9198-49a886554a85")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca")
                        },
                        new
                        {
                            CategoriesId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            SkillsId = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("a9050e0d-59c4-eded-868e-1db3ef6d8219")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("44523004-a916-44bd-8593-14649a52bb4d")
                        },
                        new
                        {
                            CategoriesId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            SkillsId = new Guid("c225634f-97c8-c659-97f2-629c12199f07")
                        },
                        new
                        {
                            CategoriesId = new Guid("572ba72e-87df-45bf-9496-a2b9d8962c7d"),
                            SkillsId = new Guid("c225634f-97c8-c659-97f2-629c12199f07")
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("572ba72e-87df-45bf-9496-a2b9d8962c7d"),
                            DisplayColor = "#000000",
                            Name = "Arcane Magic"
                        },
                        new
                        {
                            Id = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            DisplayColor = "#000000",
                            Name = "Body Enhancement"
                        },
                        new
                        {
                            Id = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            DisplayColor = "#000000",
                            Name = "Healing Magic"
                        },
                        new
                        {
                            Id = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            DisplayColor = "#000000",
                            Name = "Cosmic Magic"
                        },
                        new
                        {
                            Id = new Guid("cdb7b315-0277-451c-9ff0-ea5f1fce8c25"),
                            DisplayColor = "#000000",
                            Name = "Aura"
                        },
                        new
                        {
                            Id = new Guid("f8362bfc-6004-43df-827f-17f21203c6f3"),
                            DisplayColor = "#000000",
                            Name = "Teleportation Magic"
                        },
                        new
                        {
                            Id = new Guid("65728378-090f-4c29-9e87-b282f489d028"),
                            DisplayColor = "#000000",
                            Name = "Perception Aura"
                        },
                        new
                        {
                            Id = new Guid("b1cbe616-e004-4b34-97eb-3d11d2f5f059"),
                            DisplayColor = "#000000",
                            Name = "Ashen Magic"
                        },
                        new
                        {
                            Id = new Guid("29543eb0-73d9-4fd5-8abc-1ebd3c92d9e3"),
                            DisplayColor = "#000000",
                            Name = "Fire Magic"
                        },
                        new
                        {
                            Id = new Guid("e5451fe8-a092-45bf-9bbd-728fb10ed6ff"),
                            DisplayColor = "#000000",
                            Name = "Space Magic"
                        },
                        new
                        {
                            Id = new Guid("f8f302ab-7ed7-47a9-85c1-2d570478a99a"),
                            DisplayColor = "#000000",
                            Name = "Flesh Magic"
                        },
                        new
                        {
                            Id = new Guid("4538069f-9680-4b26-84a4-e608d1c86606"),
                            DisplayColor = "#000000",
                            Name = "Mind Magic"
                        },
                        new
                        {
                            Id = new Guid("12696ef5-a857-466f-a618-43ee092816ee"),
                            DisplayColor = "#000000",
                            Name = "Ice Magic"
                        },
                        new
                        {
                            Id = new Guid("94cb02e4-43dc-4021-95ac-d9d5bc6512d6"),
                            DisplayColor = "#000000",
                            Name = "Lava Magic"
                        },
                        new
                        {
                            Id = new Guid("11751928-c2d3-4939-9692-05f578af3d00"),
                            DisplayColor = "#000000",
                            Name = "Earth Magic"
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterStatusId");

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Level = 1004,
                            Name = "The Cosmic Immortal"
                        },
                        new
                        {
                            Id = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Level = 1001,
                            Name = "The Pyroclastic Storm"
                        },
                        new
                        {
                            Id = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Level = 1002,
                            Name = "The Sunforged Realmwalker"
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UnspentStatpoints")
                        .HasColumnType("int");

                    b.Property<Guid>("UserCharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserCharacterId");

                    b.ToTable("CharacterStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 4, 4, 14, 13, 15, 976, DateTimeKind.Unspecified).AddTicks(3422), new TimeSpan(0, 0, 0, 0, 0)),
                            UnspentStatpoints = 25,
                            UserCharacterId = new Guid("0da44e54-90ea-4ad0-a409-ea0cb1d38c4a")
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.ClassModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AffectedResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryCalculationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercentagePointsOfCategoryIncrease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffectedResourceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassModifiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2218f3c7-591f-40eb-9f48-38b4f958440d"),
                            AffectedResourceId = new Guid("97f54c26-273e-47fc-b00f-7c5ad5b6cfae"),
                            CategoryCalculationType = 4,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Your mana capacity is multiplied by five",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("20ac1928-5cff-4504-a926-e253c38891d8"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Body enhancement magic is improved by 500%",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("c2ef6ecc-a8ba-4d0c-a9fd-f0d3dfcf11cf"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "All healing magic skills are improved by 500%",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("c37f99aa-4fe2-4ea0-9cbe-63a646a26d1a"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("842269cc-6ac4-4c91-8e86-66787ed92c8c"),
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "All cosmic magic skills are improved by 250%",
                            PercentagePointsOfCategoryIncrease = 250
                        },
                        new
                        {
                            Id = new Guid("26d1fd63-e8ce-47ff-9587-b43948baf4d5"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Natural health regeneration is increased by 1% per minute",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("a9f8276e-272e-443d-a161-549e43525cce"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Natural mana regeneration is increased by 1% per minute",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("6d66a14d-e883-4704-bc2d-8acbfbefecad"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Food, water and sleep needed to sustain yourself are no longer required",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("d9c0563a-a568-4809-b798-bdf387475b38"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "You do not age",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("4a356fc3-234a-4e1e-9091-210132ff23d1"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "You can absorb and use 25% of the ambient mana around you",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("e58a8112-38b5-4970-b38d-53866b4c8543"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "All mana regeneration increases by 1% to a maximum of 100% for every second you are not hit by an enemy attack",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("5274cf3c-f1cb-4fc8-8175-8f202d7d47c3"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "Excess generated mana instead charges a second mana pool equaling your total health [0/125400]. Mana from this pool can be transferred into your main mana pool at will",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("1d2154a7-a236-4afa-b9cc-5f913c5a6468"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Description = "You may infuse any barrier, wall, or magical armor with cosmic energy",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("988af334-4b7e-4c7e-ae51-c5f3362ae0ef"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "Body enhancement magic is improved by 500%",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("ea583586-3ebb-4680-9092-250882d6c90f"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("b1cbe616-e004-4b34-97eb-3d11d2f5f059"),
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "All Ashen magic skills are improved by 500%",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("a37dff49-7a62-4355-b6d4-7dccc452a247"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("29543eb0-73d9-4fd5-8abc-1ebd3c92d9e3"),
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "All Fire magic skills are improved by 250%",
                            PercentagePointsOfCategoryIncrease = 250
                        },
                        new
                        {
                            Id = new Guid("9d0ab750-a179-4107-8349-e17d2d4dc88e"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "All fighting styles using hand to hand combat are more refined",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("268eb8e9-5be0-4d4d-b29d-0ce1f6bcacca"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "Your will is ash and heat",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("1382a487-16d5-4356-b1a2-a391cbaa7f53"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "You cannot be stunned by enemy attacks",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("6db597af-34bb-4660-ac70-e7d9bb482088"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "Your bones and muscles have vastly increased density",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("29185439-b3d7-4648-847d-7709cb46faa1"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("453c74bc-e480-44c2-82ea-13e3e49f821b"),
                            Description = "Your heat generation is increased by 1000%",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("a070e26f-c73c-487f-9fdd-d73286650e22"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("e5451fe8-a092-45bf-9bbd-728fb10ed6ff"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Space Magic is improved by 500%",
                            PercentagePointsOfCategoryIncrease = 500
                        },
                        new
                        {
                            Id = new Guid("09e97cee-34b2-4aea-9b47-b7160339de10"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Resilience is increased by 500%",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("fe07af4f-38e6-4e99-9f9d-3bd29692bded"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("b28d8f6f-6ea3-4640-a3d3-acf857dbc00b"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Body Enhancement Magic is improved by 300%",
                            PercentagePointsOfCategoryIncrease = 300
                        },
                        new
                        {
                            Id = new Guid("53b6d5e7-cd28-45a4-a7c8-72cc361b8e9b"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("29543eb0-73d9-4fd5-8abc-1ebd3c92d9e3"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Fire Magic is improved by 200%",
                            PercentagePointsOfCategoryIncrease = 200
                        },
                        new
                        {
                            Id = new Guid("8bb31795-7294-42f3-9347-1e8b31596065"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("f8f302ab-7ed7-47a9-85c1-2d570478a99a"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Flesh Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("a24ac0ce-4fc0-4f2c-ae22-dbed4a108808"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("a9a1f9c4-f80b-4a14-a9e4-82751f95c972"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Healing Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("2af0ee40-2ea0-4b2c-abc6-22a15b37fb19"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("4538069f-9680-4b26-84a4-e608d1c86606"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Mind Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("d2168950-990e-42d5-9b43-8b556aeb4741"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("12696ef5-a857-466f-a618-43ee092816ee"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Ice Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("2cc5563c-4e6f-4785-9d7a-f334fc6600aa"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("94cb02e4-43dc-4021-95ac-d9d5bc6512d6"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Lava Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("6c72a67a-beff-4d01-a746-3350677d2832"),
                            CategoryCalculationType = 0,
                            CategoryId = new Guid("11751928-c2d3-4939-9692-05f578af3d00"),
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Earth Magic is improved by 100%",
                            PercentagePointsOfCategoryIncrease = 100
                        },
                        new
                        {
                            Id = new Guid("a0ee0c09-5d9f-4577-9d16-c597fb97d36d"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Your Soul has been strengthened by the Primordial Flame",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("cb4fb181-c7a8-4007-afdf-e68bcf328c9b"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Your skin grows more resilient",
                            PercentagePointsOfCategoryIncrease = 0
                        },
                        new
                        {
                            Id = new Guid("9c725771-e1b1-4a34-a2bf-db707b546077"),
                            CategoryCalculationType = 0,
                            ClassId = new Guid("6689fb11-732c-4fda-af01-abde9895dc16"),
                            Description = "Greatly increases the heat you can store within your body and soul",
                            PercentagePointsOfCategoryIncrease = 0
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseStatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourcePointsPerBaseStatPoint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatId");

                    b.HasIndex("CharacterStatusId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70eaef56-21c1-494d-a0ba-312478c19428"),
                            BaseStatId = new Guid("1bf1d8dd-7cc3-486d-bb26-0bde4ee439df"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Health",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("f8a10c54-df2b-4658-9e37-ff772a55aea3"),
                            BaseStatId = new Guid("ab85915d-e66f-4460-96af-e90f171ccab5"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Stamina",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("97f54c26-273e-47fc-b00f-7c5ad5b6cfae"),
                            BaseStatId = new Guid("c6474033-2e4c-4805-95f3-4fe22e9de88a"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Mana",
                            ResourcePointsPerBaseStatPoint = 10
                        },
                        new
                        {
                            Id = new Guid("741e7652-0c8e-4cb8-8ac4-b298637ae6c2"),
                            BaseStatId = new Guid("1bf1d8dd-7cc3-486d-bb26-0bde4ee439df"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            DisplayName = "Mana (Essence)",
                            ResourcePointsPerBaseStatPoint = 10
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enhanced")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Cosmic Deconstruction",
                            Tier = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 1,
                            Name = "True Reconstruction",
                            Tier = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Embodiment of the Arcane",
                            Tier = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e8b05991-c7f1-faf9-91e1-d525370c912c"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Teleportation",
                            Tier = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Limitless Domain",
                            Tier = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7c893d4b-246d-c304-9198-49a886554a85"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Catalyst Core",
                            Tier = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Timeless Perception",
                            Tier = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a9050e0d-59c4-eded-868e-1db3ef6d8219"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = true,
                            Level = 30,
                            Name = "Cycle of Creation",
                            Tier = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("44523004-a916-44bd-8593-14649a52bb4d"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = false,
                            Level = 30,
                            Name = "Eternal Huntress",
                            Tier = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c225634f-97c8-c659-97f2-629c12199f07"),
                            CharacterClassId = new Guid("c2782453-16ab-4d52-923d-97c6a2b40029"),
                            Enhanced = false,
                            Level = 30,
                            Name = "Eternal Brawling",
                            Tier = 3,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.SkillVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseValue")
                        .HasColumnType("int");

                    b.Property<string>("BaseVariableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryCalculationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VariableCalculationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillVariables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1fb8625-1c43-d417-b348-9188627e0039"),
                            BaseValue = 100,
                            CategoryCalculationType = 1,
                            Name = "stats_increase",
                            SkillId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            Unit = "%",
                            VariableCalculationType = 1
                        },
                        new
                        {
                            Id = new Guid("bc45890e-5397-5d1a-9666-afde67a9c7ea"),
                            BaseValue = 25,
                            BaseVariableName = "stats_increase",
                            CategoryCalculationType = 1,
                            Name = "wisdom_increase",
                            SkillId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            Unit = "%",
                            VariableCalculationType = 3
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SkillVariableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterStatusId");

                    b.HasIndex("SkillVariableId");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bf1d8dd-7cc3-486d-bb26-0bde4ee439df"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Vitality",
                            Value = 3800
                        },
                        new
                        {
                            Id = new Guid("ab85915d-e66f-4460-96af-e90f171ccab5"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Endurance",
                            Value = 600
                        },
                        new
                        {
                            Id = new Guid("de4b423f-4718-4e26-9d75-14f4a1581b37"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Strength",
                            Value = 860
                        },
                        new
                        {
                            Id = new Guid("20cce93e-f883-4860-be2f-4cdbd0c6e3be"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Dexterity",
                            Value = 610
                        },
                        new
                        {
                            Id = new Guid("047e7614-496d-4519-a784-6dec5e753571"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Intelligence",
                            Value = 3770
                        },
                        new
                        {
                            Id = new Guid("c6474033-2e4c-4805-95f3-4fe22e9de88a"),
                            CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                            Name = "Wisdom",
                            Value = 4000
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.TierDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("TierDescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d33a7d6c-37b9-6bab-a900-c5d931fcf99a"),
                            Description = "Send a pulse of deconstructing cosmic power into an object, spell, or creature within your domain with every motion using your arms, fists, fingers, legs, feet, or head. Your Intelligence stat enhances the damage potential.",
                            SkillId = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("aa1bf3e6-8d3d-d9c3-85de-994083b25ed6"),
                            Description = "The amount of mana used per pulse can be regulated with a maximum of 5000 mana per pulse. You may charge each pulse with 5000 mana per second to a maximum of 25000 mana. Once cosmic power resides within a target, you can rip it out with a reversed motion to cause additional damage. Cosmic power within a target stacks, depending on their defensive measures and structure.",
                            SkillId = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("4ddda253-7eb1-5660-a823-819834356edb"),
                            Description = "You may choose to use Cosmic Deconstruction as a non intrusive attack, instead sending out a broad wave of deconstructing energy from you at the center. The same motion requirements as in the first tier apply. If used as a wave, the range of Cosmic Deconstruction is equal to the range of your domain and is more effective against magical constructs.",
                            SkillId = new Guid("3302cea7-668b-4275-81df-e22dd8ad36f3"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("418575d1-af0a-fbdf-8342-05a04eff4669"),
                            Description = "Send a healing pulse of cosmic power into yourself or creatures within your domain. This skill can be channeled. In addition to health, True Reconstruction restores mana and heals damage to your soul.",
                            SkillId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("fbf2babb-dab1-dcce-b97d-83c2de127e78"),
                            Description = "Your control is increased greatly, you can now focus your healing on specific parts of the body. As long as mana and health remains, your True Reconstruction will restore your body. Lose your head and see for yourself! Health loss and critical blows are recalculated due to the nature of your healing. You may restore magical constructs and enchantments with True Reconstruction.",
                            SkillId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("fe06af7a-5aa0-6269-a1c9-c08ea3d528e4"),
                            Description = "You have healed your body time and time again, knowing every cell and where it belongs. Sacrifice a large amount of mana to rush your healing to unprecedented speeds. Lack of knowledge about your body may result in heavy damage. Effect can be used on any creature or magical construct. Limited to 10’000 mana per use.",
                            SkillId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("df9b38f1-387c-fd76-b8f9-fbb8fe7551a2"),
                            Description = "You have healed yourself thousands of times. Have regrown lost limbs, have reformed lost organs. You have healed and protected your mind, all in pursuit of greater power. Healing to shield you. Healing to allow an exchange of blows, with those you would not otherwise be able to fight. A core ability for the Azarinth Healer, a terrifying tool for the Cosmic Immortal. You have grasped the true nature of Reconstruction. Not the healing spell of a savior, but a necessity for the battle healer you have become. Through the fourth tier, you have enhanced this ability to the pinnacle. Once active, cosmic energies will surge within your body. Not to heal wounds you have sustained, but to keep you fighting whatever enemy you face. To overwhelm the foes no other could dare stand against.\r\nIf you reach 0 points of health, all remaining mana is used to activate True Reconstruction, containing your essence in a set of powerful cosmic barriers protecting your remains from harm and restoring your life. This effect may activate once every 24 hours.\r\nFollowing benefits and changes will apply during use of the fourth tier:\r\n- All damage sustained is dealt to your mana instead of your health\r\n- The first stage of True Reconstruction will generate additional mana and health\r\n- All mana generation and absorption is doubled\r\n- Your body is pushed to the limits of cosmic power, enhancing all of your abilities\r\n- Your body sustains heavy damage from this flow of cosmic power. This ability will deactivate when your health drops below a certain point [1% - Set value] and cannot be used again for twice as long as it has been active\r\n- Once the 4th tier deactivates, a set of seven cosmic barriers appear around you to protect from enemy blows. You may control these barriers or allow them to automatically react to enemy attacks\r\n- You cannot use the third tier of True Reconstruction on your own body",
                            SkillId = new Guid("573f7b5f-c131-4786-8eb4-b9014aa88224"),
                            Tier = 3
                        },
                        new
                        {
                            Id = new Guid("4936c8dd-2a26-6e34-85b3-361bec90a47b"),
                            Description = "Your body glows with the power of the cosmos, increasing your resilience, speed, Intelligence, and Strength by <stats_increase>.",
                            SkillId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("a4e646d4-ddd0-5cbb-afa3-e6e378ddca1a"),
                            Description = "Your sight, hearing and sense of smell is also affected by Embodiment of the Arcane.",
                            SkillId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("c43f0039-1859-f115-89bd-11cce7b380f6"),
                            Description = "You are one with the Arcane. The skill’s upkeep has been removed. A static <wisdom_increase> of the base effect is applied to Wisdom. Does not affect the mana regeneration properties of the Wisdom stat.",
                            SkillId = new Guid("2c8b0955-013f-5453-b0e8-843725a1587e"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("c2e9b624-7d81-4052-b8ae-47196a55f8b7"),
                            Description = "Immediately appear anywhere in your domain or anywhere you can see with reliable clarity.",
                            SkillId = new Guid("e8b05991-c7f1-faf9-91e1-d525370c912c"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("c0136e61-f935-e3b0-b8d7-0d5f2aab376a"),
                            Description = "The time between transfers is reduced greatly. No ground contact needed between transfers. Teleportation gains 3 charges, each with a separate cooldown. For 2 seconds after Teleportation is used, you may return to the original position in the fabric where the spell was initially activated.",
                            SkillId = new Guid("e8b05991-c7f1-faf9-91e1-d525370c912c"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("e128a92f-5c38-d0a8-8675-1878d757135d"),
                            Description = "You may set ten destinations you touch. You may change each destination once per day. This cooldown is static. You may travel to each destination once every 25 minutes [12.5 minutes]. Cast time is reduced by a static 50% for destinations you have already teleported to.",
                            SkillId = new Guid("e8b05991-c7f1-faf9-91e1-d525370c912c"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("e454dd96-a075-757f-a4d2-5bc3707e1461"),
                            Description = "Perceive everything in a sphere around you while this skill is activated. The higher the level the further your domain reaches. You may drain mana from creatures and spells within your domain.",
                            SkillId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("988e506d-2e2b-70d1-a511-a7619e378ae1"),
                            Description = "Arcane dominion opens your senses to the arcane. A paramount skill both on and off the battlefield. Elements and spells you control within your dominion have increased harmony. You drain the remaining mana from creatures you kill inside of your domain.",
                            SkillId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("1bd0238a-1404-5ec0-a614-7ecd1cd9aee5"),
                            Description = "Your element manipulation skills are improved by a static 100% when used within your dominion. Improves any of your mana absorption or drain abilities within your domain.",
                            SkillId = new Guid("9e6f3616-a2b1-7643-b9f3-713c472f9dee"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("5e631c2d-3bf0-f06b-94e9-d700ae12aa70"),
                            Description = "Your body was changed by magic. All pain is reduced greatly. Your body is 75% [1387.5%] more durable. You heal even fatal injuries without help of healing magic. Your natural Health and Mana regeneration is improved by 150% [2775%].",
                            SkillId = new Guid("7c893d4b-246d-c304-9198-49a886554a85"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("decc6a24-5bfd-4526-a9a8-34d5656c6450"),
                            Description = "The magic of the cosmos settles inside your body. Your resistance to magical, physical, and soul damage is increased by a static 35% [647.5%]. Your bones and muscles are five times as dense.",
                            SkillId = new Guid("7c893d4b-246d-c304-9198-49a886554a85"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("fde2e4d4-4b21-d2f1-b7cc-b9d8a31f39c7"),
                            Description = "Your body was battered and forged by magic. You absorb mana from enemy spells in your domain. Efficiency is determined by enemy mana used and your resistance to the type of magic. Mana cost for all skills reduced by a static 35%. Your body can absorb ambient mana. Amount dependent on availability and harmony.",
                            SkillId = new Guid("7c893d4b-246d-c304-9198-49a886554a85"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("0af7d155-74d7-f64c-811d-78967b0a6586"),
                            Description = "Vastly increases your perception and reflexes.",
                            SkillId = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("c0bcf18e-d71b-771d-87f4-c011c0bac18d"),
                            Description = "Timeless Perception spikes for two seconds, should you be about to receive a blow that would take 50% or more of your health, or should your mind be incapacitated with an incoming blow. This can happen only once per hour.",
                            SkillId = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("a25a83ba-9204-6a25-92d8-9911e43de6fa"),
                            Description = "Your resilience and speed is doubled during the spike in perception. Increases usage to five times per hour. The effect duration is increased to three seconds and can be activated at will. You gain the ability to gauge enemy mana usage and may learn how strongly a direct hit of a spell will impact you. Increased ability to gauge incoming damage depending on your familiarity with the respective magic type.",
                            SkillId = new Guid("8340dbd8-311f-7131-97cb-a4d38bfaaeca"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("be1dafb2-60dd-f37c-8cea-89e6cfb1a489"),
                            Description = "You have learned of Cosmic Deconstruction and True Reconstruction. Now you will learn of their Reversal.\r\nUpon activation, Cosmic Deconstruction will send a part of the struck enemy’s health and mana into yourself. No mana will be released on impact, rendering Cosmic Deconstruction’s offensive potential to zero.\r\nUpon activation, True Reconstruction will send a destructive force of channeled mana into yourself, a creature or magical construct within your domain, the healing aspects are reduced to zero.",
                            SkillId = new Guid("a9050e0d-59c4-eded-868e-1db3ef6d8219"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("790c0229-a574-c24f-9889-b7c5a5fb6635"),
                            Description = "You may have both the original and reversed aspects activated at the same time. When an enemy partially or fully resists either Cosmic Deconstruction or True Reconstruction, you absorb the dissipating mana.",
                            SkillId = new Guid("a9050e0d-59c4-eded-868e-1db3ef6d8219"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("ef19f675-4468-f513-976d-ee4e447e3dd0"),
                            Description = "Healing, power, resilience and speed. All requires balance. Your respective Deconstruction and Reconstruction spells have their potency increased by a static 25% of your median stat value. [488.75%]. You may channel health in addition to mana into the respective offensive uses of Archon Strike and Sentinel Reconstruction. Health cost to activate effects is reduced by a static 20%.",
                            SkillId = new Guid("a9050e0d-59c4-eded-868e-1db3ef6d8219"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("241a8992-f096-5b79-89f4-78faee6171e5"),
                            Description = "Huntress turned Eternal. Your eyes are unmatched and so is your nose. Perceive the smallest irregularities in your surroundings as well as the ambient mana to find clues about your target’s whereabouts. Perceive the trails of dangerous prey.",
                            SkillId = new Guid("44523004-a916-44bd-8593-14649a52bb4d"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("ed178ddc-382e-54c1-85ee-c78c31d936d6"),
                            Description = "You gain a sense for the distress in the people around you. Amplify this by sacrificing mana. You gain a sense for the arcane, feeling even minor spells around you. As you practice to differentiate these spells, you will learn of their intent.",
                            SkillId = new Guid("44523004-a916-44bd-8593-14649a52bb4d"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("21dd3291-fe0f-5da8-86a7-3e6b5f64ea93"),
                            Description = "Through Azarinth magic, you may mark an enemy or ally with the Eternal Mark. Allies may use the mark to send a short message to the Arcane Eternal once per day. The Arcane Eternal can send a short message to each non forcefully applied mark once per day. Each level in the third tier adds two additional marks that can be used. Marks forcefully applied have a limited duration.",
                            SkillId = new Guid("44523004-a916-44bd-8593-14649a52bb4d"),
                            Tier = 2
                        },
                        new
                        {
                            Id = new Guid("ddbd2bce-3b0a-54ed-9529-2f298941cfcd"),
                            Description = "You have adapted the fighting style of the Azarinth school to something you now call your own. Damage inflicted with your own body and related skills is 110% [990%] higher. Your arms, fists, fingers, legs, and head deal a slight amount of arcane damage with each strike.",
                            SkillId = new Guid("c225634f-97c8-c659-97f2-629c12199f07"),
                            Tier = 0
                        },
                        new
                        {
                            Id = new Guid("6b34230d-8f62-ea19-a653-74387cb50011"),
                            Description = "Getting used to fighting in close quarters, your reaction time is increased to accommodate your increasing speed and control. Your bones are steeped with mana, increasing both their weight and resilience two fold.",
                            SkillId = new Guid("c225634f-97c8-c659-97f2-629c12199f07"),
                            Tier = 1
                        },
                        new
                        {
                            Id = new Guid("13c6338f-9536-d44b-9fe5-513a4e7c278c"),
                            Description = "Eternal Brawling consists of more than offense alone. A true brawler knows when to stand and let an enemy strike. You gain knowledge about sustained injuries and damage from incoming attacks as they happen.",
                            SkillId = new Guid("c225634f-97c8-c659-97f2-629c12199f07"),
                            Tier = 2
                        });
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.UserCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserCharacters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0da44e54-90ea-4ad0-a409-ea0cb1d38c4a")
                        });
                });

            modelBuilder.Entity("CategorySkill", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progress.Application.Persistence.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterClass", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.CharacterStatus", "CharacterStatus")
                        .WithMany("CharacterClasses")
                        .HasForeignKey("CharacterStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterStatus");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.UserCharacter", "UserCharacter")
                        .WithMany("CharacterStatuses")
                        .HasForeignKey("UserCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Progress.Application.Persistence.Entities.BasicInformation", "BasicInformation", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CharacterStatusId");

                            b1.ToTable("CharacterStatuses");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatusId");

                            b1.HasData(
                                new
                                {
                                    CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                                    Name = "Ilea Spears",
                                    Title = "Dragonslayer"
                                });
                        });

                    b.OwnsOne("Progress.Application.Persistence.Entities.UnspentSkillpoints", "UnspentSkillpoints", b1 =>
                        {
                            b1.Property<Guid>("CharacterStatusId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CoreSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("FourthTierGeneralSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("FourthTierSkillpoints")
                                .HasColumnType("int");

                            b1.Property<int>("ThirdTierGeneralSkillpoints")
                                .HasColumnType("int");

                            b1.HasKey("CharacterStatusId");

                            b1.ToTable("CharacterStatuses");

                            b1.WithOwner()
                                .HasForeignKey("CharacterStatusId");

                            b1.HasData(
                                new
                                {
                                    CharacterStatusId = new Guid("afa42078-a071-4bea-978e-f439c713848c"),
                                    CoreSkillpoints = 10,
                                    FourthTierGeneralSkillpoints = 1,
                                    FourthTierSkillpoints = 1,
                                    ThirdTierGeneralSkillpoints = 3
                                });
                        });

                    b.Navigation("BasicInformation");

                    b.Navigation("UnspentSkillpoints");

                    b.Navigation("UserCharacter");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.ClassModifier", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Resource", "AffectedResource")
                        .WithMany("AffectingClassModifiers")
                        .HasForeignKey("AffectedResourceId");

                    b.HasOne("Progress.Application.Persistence.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Progress.Application.Persistence.Entities.CharacterClass", "Class")
                        .WithMany("ClassModifiers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffectedResource");

                    b.Navigation("Category");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Resource", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Stat", "BaseStat")
                        .WithMany()
                        .HasForeignKey("BaseStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progress.Application.Persistence.Entities.CharacterStatus", null)
                        .WithMany("Resources")
                        .HasForeignKey("CharacterStatusId");

                    b.Navigation("BaseStat");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Skill", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.CharacterClass", "CharacterClass")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.SkillVariable", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Skill", "Skill")
                        .WithMany("Variables")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Stat", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.CharacterStatus", null)
                        .WithMany("Stats")
                        .HasForeignKey("CharacterStatusId");

                    b.HasOne("Progress.Application.Persistence.Entities.SkillVariable", null)
                        .WithMany("AffectedStats")
                        .HasForeignKey("SkillVariableId");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.TierDescription", b =>
                {
                    b.HasOne("Progress.Application.Persistence.Entities.Skill", "Skil")
                        .WithMany("TierDescriptions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skil");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterClass", b =>
                {
                    b.Navigation("ClassModifiers");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.CharacterStatus", b =>
                {
                    b.Navigation("CharacterClasses");

                    b.Navigation("Resources");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Resource", b =>
                {
                    b.Navigation("AffectingClassModifiers");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.Skill", b =>
                {
                    b.Navigation("TierDescriptions");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.SkillVariable", b =>
                {
                    b.Navigation("AffectedStats");
                });

            modelBuilder.Entity("Progress.Application.Persistence.Entities.UserCharacter", b =>
                {
                    b.Navigation("CharacterStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
