name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the unit test Docker image
      run: docker build . --file Dockerfile --tag progress-api:${{github.run_number}}-test --target testrunner

    - name: Run unit tests
      run: |
        id=$(docker create progress-api:${{github.run_number}}-test)
        docker start $id -a
        sudo mkdir -p /test-results/progress-api
        docker cp -r $id:/TestResults/ - > /test-results/progress-api
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests
        path: test-results/**/*.trx
        reporter: dotnet-trx
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.trx
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag progress-api:${{github.run_number}} --target final